"""initial schema (15 tables)

Revision ID: 11e9ad5422f9
Revises:
Create Date: 2026-05-21 16:47:18.657579

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11e9ad5422f9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("is_configured", sa.Boolean(), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_validation_status", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("uq_api_keys_provider", ["provider"], unique=True)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("idx_audit_action_created", ["action", "created_at"], unique=False)
        batch_op.create_index("idx_audit_created_at", ["created_at"], unique=False)

    op.create_table(
        "meetings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("audio_path", sa.Text(), nullable=False),
        sa.Column("audio_hash", sa.String(length=64), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("speaker_map", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('upload', 'realtime')", name="ck_meetings_source"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.create_index("idx_meetings_audio_hash", ["audio_hash"], unique=False)
        batch_op.create_index("idx_meetings_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_meetings_deleted_at", ["deleted_at"], unique=False)
        batch_op.create_index("idx_meetings_status", ["status"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index("uq_tags_name", ["name"], unique=True)

    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("value_type", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.create_index("uq_prefs_key", ["key"], unique=True)

    op.create_table(
        "evidences",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("parent_type", sa.String(length=16), nullable=False),
        sa.Column("parent_id", sa.String(length=32), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("speaker", sa.Text(), nullable=True),
        sa.Column("start_sec", sa.Float(), nullable=True),
        sa.Column("end_sec", sa.Float(), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("validation_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "parent_type IN ('topic', 'decision', 'action_item')", name="ck_evidences_parent_type"
        ),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidences", schema=None) as batch_op:
        batch_op.create_index("idx_evidences_meeting", ["meeting_id"], unique=False)
        batch_op.create_index("idx_evidences_parent", ["parent_type", "parent_id"], unique=False)

    op.create_table(
        "meeting_tags",
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("meeting_id", "tag_id"),
    )
    op.create_table(
        "minutes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("date_extracted", sa.Date(), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("open_questions", sa.JSON(), nullable=False),
        sa.Column("llm_provider", sa.String(length=32), nullable=False),
        sa.Column("llm_model", sa.String(length=64), nullable=False),
        sa.Column("tokens_input", sa.Integer(), nullable=False),
        sa.Column("tokens_output", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("validation_passed", sa.Boolean(), nullable=False),
        sa.Column("validation_issues", sa.JSON(), nullable=True),
        sa.Column("user_edited", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id"),
    )
    with op.batch_alter_table("minutes", schema=None) as batch_op:
        batch_op.create_index("uq_minutes_meeting_id", ["meeting_id"], unique=True)

    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=True),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stage", sa.String(length=32), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("progress_pct BETWEEN 0 AND 100", name="ck_jobs_progress"),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.create_index("idx_jobs_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_jobs_meeting_id", ["meeting_id"], unique=False)
        batch_op.create_index("idx_jobs_status", ["status"], unique=False)

    op.create_table(
        "speakers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("speaker_id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("total_speaking_sec", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.create_index("idx_speakers_meeting", ["meeting_id"], unique=False)

    op.create_table(
        "transcripts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("language_detected", sa.String(length=8), nullable=True),
        sa.Column("provider_used", sa.String(length=32), nullable=False),
        sa.Column("model_used", sa.String(length=64), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("processing_time_sec", sa.Float(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("avg_confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id"),
    )
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.create_index("idx_transcripts_meeting_id", ["meeting_id"], unique=False)

    op.create_table(
        "action_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("minute_id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assigned_to", sa.Text(), nullable=True),
        sa.Column("deadline_raw", sa.Text(), nullable=True),
        sa.Column("deadline_parsed", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("evidence_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high')", name="ck_action_items_priority"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'done', 'cancelled')", name="ck_action_items_status"
        ),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["minute_id"], ["minutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index("idx_actions_deadline", ["deadline_parsed"], unique=False)
        batch_op.create_index("idx_actions_meeting_id", ["meeting_id"], unique=False)
        batch_op.create_index("idx_actions_minute_id", ["minute_id"], unique=False)
        batch_op.create_index("idx_actions_status", ["status"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("minute_id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidences.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["minute_id"], ["minutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index("idx_decisions_meeting_id", ["meeting_id"], unique=False)
        batch_op.create_index("idx_decisions_minute_id", ["minute_id"], unique=False)

    op.create_table(
        "minute_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("minute_id", sa.String(length=32), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("change_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["minute_id"], ["minutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("minute_versions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_versions_minute_created", ["minute_id", "created_at"], unique=False
        )

    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transcript_id", sa.String(length=32), nullable=False),
        sa.Column("meeting_id", sa.String(length=32), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("start_sec", sa.Float(), nullable=False),
        sa.Column("end_sec", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("speaker_id", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcripts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index("idx_segments_meeting_id", ["meeting_id"], unique=False)
        batch_op.create_index(
            "idx_segments_transcript_start", ["transcript_id", "start_sec"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index("idx_segments_transcript_start")
        batch_op.drop_index("idx_segments_meeting_id")

    op.drop_table("transcript_segments")
    with op.batch_alter_table("minute_versions", schema=None) as batch_op:
        batch_op.drop_index("idx_versions_minute_created")

    op.drop_table("minute_versions")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index("idx_decisions_minute_id")
        batch_op.drop_index("idx_decisions_meeting_id")

    op.drop_table("decisions")
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index("idx_actions_status")
        batch_op.drop_index("idx_actions_minute_id")
        batch_op.drop_index("idx_actions_meeting_id")
        batch_op.drop_index("idx_actions_deadline")

    op.drop_table("action_items")
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.drop_index("idx_transcripts_meeting_id")

    op.drop_table("transcripts")
    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.drop_index("idx_speakers_meeting")

    op.drop_table("speakers")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_jobs_status")
        batch_op.drop_index("idx_jobs_meeting_id")
        batch_op.drop_index("idx_jobs_created_at")

    op.drop_table("processing_jobs")
    with op.batch_alter_table("minutes", schema=None) as batch_op:
        batch_op.drop_index("uq_minutes_meeting_id")

    op.drop_table("minutes")
    op.drop_table("meeting_tags")
    with op.batch_alter_table("evidences", schema=None) as batch_op:
        batch_op.drop_index("idx_evidences_parent")
        batch_op.drop_index("idx_evidences_meeting")

    op.drop_table("evidences")
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_index("uq_prefs_key")

    op.drop_table("user_preferences")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("uq_tags_name")

    op.drop_table("tags")
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_index("idx_meetings_status")
        batch_op.drop_index("idx_meetings_deleted_at")
        batch_op.drop_index("idx_meetings_created_at")
        batch_op.drop_index("idx_meetings_audio_hash")

    op.drop_table("meetings")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("idx_audit_created_at")
        batch_op.drop_index("idx_audit_action_created")

    op.drop_table("audit_log")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("uq_api_keys_provider")

    op.drop_table("api_keys")
    # ### end Alembic commands ###
