-- ============================================================
-- Eskuta -- Migration 001: schema inicial (15 tabelas)
--
-- Bilingue: roda tanto em SQLite quanto em Postgres.
--   - SQLite: usado em dev/MVP via Alembic (fonte da verdade).
--   - Postgres: aplicar manualmente em produção (Fase 3).
--
-- Origem: gerado por Alembic a partir dos models em app/models/.
-- DATETIME foi substituído por TIMESTAMP (ambos SGBDs aceitam).
-- Para produção Postgres:
--   * INTEGER PRIMARY KEY -> use GENERATED BY DEFAULT AS IDENTITY
--     ou SERIAL nas colunas autoincrement (api_keys.id, audit_log.id,
--     tags.id, user_preferences.id).
--   * JSON -> JSONB (Postgres prefere JSONB; SQLite armazena como TEXT).
-- ============================================================

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);


CREATE TABLE api_keys (
    id INTEGER NOT NULL,
    provider VARCHAR(32) NOT NULL,
    is_configured BOOLEAN NOT NULL,
    last_validated_at TIMESTAMP,
    last_validation_status VARCHAR(16),
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (provider)
);

CREATE UNIQUE INDEX uq_api_keys_provider ON api_keys (provider);

CREATE TABLE audit_log (
    id INTEGER NOT NULL,
    action VARCHAR(64) NOT NULL,
    entity_type VARCHAR(32),
    entity_id VARCHAR(64),
    metadata JSON,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_audit_action_created ON audit_log (action, created_at);

CREATE INDEX idx_audit_created_at ON audit_log (created_at);

CREATE TABLE meetings (
    id VARCHAR(32) NOT NULL,
    title TEXT,
    original_filename TEXT,
    audio_path TEXT NOT NULL,
    audio_hash VARCHAR(64) NOT NULL,
    duration_sec FLOAT,
    file_size_bytes INTEGER,
    language VARCHAR(8) NOT NULL,
    source VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    speaker_map JSON,
    metadata JSON,
    started_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_meetings_source CHECK (source IN ('upload', 'realtime'))
);

CREATE INDEX idx_meetings_audio_hash ON meetings (audio_hash);

CREATE INDEX idx_meetings_created_at ON meetings (created_at);

CREATE INDEX idx_meetings_deleted_at ON meetings (deleted_at);

CREATE INDEX idx_meetings_status ON meetings (status);

CREATE TABLE tags (
    id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    color VARCHAR(16),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE UNIQUE INDEX uq_tags_name ON tags (name);

CREATE TABLE user_preferences (
    id INTEGER NOT NULL,
    "key" VARCHAR(64) NOT NULL,
    value TEXT NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    UNIQUE ("key")
);

CREATE UNIQUE INDEX uq_prefs_key ON user_preferences ("key");

CREATE TABLE evidences (
    id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    parent_type VARCHAR(16) NOT NULL,
    parent_id VARCHAR(32) NOT NULL,
    quote TEXT NOT NULL,
    speaker TEXT,
    start_sec FLOAT,
    end_sec FLOAT,
    validated BOOLEAN NOT NULL,
    validation_score FLOAT,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_evidences_parent_type CHECK (parent_type IN ('topic', 'decision', 'action_item')),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE
);

CREATE INDEX idx_evidences_meeting ON evidences (meeting_id);

CREATE INDEX idx_evidences_parent ON evidences (parent_type, parent_id);

CREATE TABLE meeting_tags (
    meeting_id VARCHAR(32) NOT NULL,
    tag_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (meeting_id, tag_id),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY(tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE minutes (
    id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    title TEXT NOT NULL,
    date_extracted DATE,
    executive_summary TEXT NOT NULL,
    participants JSON NOT NULL,
    topics JSON NOT NULL,
    open_questions JSON NOT NULL,
    llm_provider VARCHAR(32) NOT NULL,
    llm_model VARCHAR(64) NOT NULL,
    tokens_input INTEGER NOT NULL,
    tokens_output INTEGER NOT NULL,
    cost_usd NUMERIC(10, 6) NOT NULL,
    validation_passed BOOLEAN NOT NULL,
    validation_issues JSON,
    user_edited BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    UNIQUE (meeting_id)
);

CREATE UNIQUE INDEX uq_minutes_meeting_id ON minutes (meeting_id);

CREATE TABLE processing_jobs (
    id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    job_type VARCHAR(32) NOT NULL,
    current_stage VARCHAR(32),
    progress_pct INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    error_message TEXT,
    error_stage VARCHAR(32),
    retry_count INTEGER NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ck_jobs_progress CHECK (progress_pct BETWEEN 0 AND 100),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE
);

CREATE INDEX idx_jobs_created_at ON processing_jobs (created_at);

CREATE INDEX idx_jobs_meeting_id ON processing_jobs (meeting_id);

CREATE INDEX idx_jobs_status ON processing_jobs (status);

CREATE TABLE speakers (
    id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    speaker_id VARCHAR(32) NOT NULL,
    display_name TEXT,
    total_speaking_sec FLOAT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE
);

CREATE INDEX idx_speakers_meeting ON speakers (meeting_id);

CREATE TABLE transcripts (
    id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    full_text TEXT NOT NULL,
    language_detected VARCHAR(8),
    provider_used VARCHAR(32) NOT NULL,
    model_used VARCHAR(64) NOT NULL,
    cost_usd NUMERIC(10, 6) NOT NULL,
    processing_time_sec FLOAT,
    word_count INTEGER,
    avg_confidence FLOAT,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    UNIQUE (meeting_id)
);

CREATE INDEX idx_transcripts_meeting_id ON transcripts (meeting_id);

CREATE TABLE action_items (
    id VARCHAR(32) NOT NULL,
    minute_id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    assigned_to TEXT,
    deadline_raw TEXT,
    deadline_parsed DATE,
    priority VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    evidence_id VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT ck_action_items_priority CHECK (priority IN ('low', 'normal', 'high')),
    CONSTRAINT ck_action_items_status CHECK (status IN ('pending', 'done', 'cancelled')),
    FOREIGN KEY(evidence_id) REFERENCES evidences (id) ON DELETE SET NULL,
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY(minute_id) REFERENCES minutes (id) ON DELETE CASCADE
);

CREATE INDEX idx_actions_deadline ON action_items (deadline_parsed);

CREATE INDEX idx_actions_meeting_id ON action_items (meeting_id);

CREATE INDEX idx_actions_minute_id ON action_items (minute_id);

CREATE INDEX idx_actions_status ON action_items (status);

CREATE TABLE decisions (
    id VARCHAR(32) NOT NULL,
    minute_id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    evidence_id VARCHAR(32),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(evidence_id) REFERENCES evidences (id) ON DELETE SET NULL,
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY(minute_id) REFERENCES minutes (id) ON DELETE CASCADE
);

CREATE INDEX idx_decisions_meeting_id ON decisions (meeting_id);

CREATE INDEX idx_decisions_minute_id ON decisions (minute_id);

CREATE TABLE minute_versions (
    id VARCHAR(32) NOT NULL,
    minute_id VARCHAR(32) NOT NULL,
    version_number INTEGER NOT NULL,
    snapshot_json JSON NOT NULL,
    change_reason VARCHAR(64),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(minute_id) REFERENCES minutes (id) ON DELETE CASCADE
);

CREATE INDEX idx_versions_minute_created ON minute_versions (minute_id, created_at);

CREATE TABLE transcript_segments (
    id INTEGER NOT NULL,
    transcript_id VARCHAR(32) NOT NULL,
    meeting_id VARCHAR(32) NOT NULL,
    segment_index INTEGER NOT NULL,
    start_sec FLOAT NOT NULL,
    end_sec FLOAT NOT NULL,
    text TEXT NOT NULL,
    speaker_id VARCHAR(32),
    confidence FLOAT,
    PRIMARY KEY (id),
    FOREIGN KEY(meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY(transcript_id) REFERENCES transcripts (id) ON DELETE CASCADE
);

CREATE INDEX idx_segments_meeting_id ON transcript_segments (meeting_id);

CREATE INDEX idx_segments_transcript_start ON transcript_segments (transcript_id, start_sec);

INSERT INTO alembic_version (version_num) VALUES ('11e9ad5422f9') RETURNING version_num;
